HesidosWebsite/Areas/Admin/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HesidosWebsite.Class;

namespace HesidosWebsite.Areas.Admin.Controllers
{
    [Authorize(Roles = ServerRoles.Admin)]
    public class AdminController : Controller
    {
        // GET: Admin/Admin
        public ActionResult ServerRestart()
        {
            if (Request.IsAjaxRequest())
            {
                return PartialView();
            }
            return View();
        }

        public ActionResult Annoucement()
        {
            if (Request.IsAjaxRequest())
            {
                return PartialView();
            }
            return View();
        }
    }
}

HesidosWebsite/Areas/Admin/Controllers/GamemasterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HesidosWebsite.Class;

namespace HesidosWebsite.Areas.Admin.Controllers
{
    [Authorize(Roles = ServerRoles.GameMaster)]
    public class GamemasterController : Controller
    {
        // GET: Admin/Gamemaster
        public ActionResult LiveMap()
        {
            if (Request.IsAjaxRequest())
            {
                return PartialView();
            }
            return View();
        }

        public ActionResult Punishments()
        {
            if (Request.IsAjaxRequest())
            {
                return PartialView();
            }
            return View();
        }
    }
}

HesidosWebsite/Areas/Admin/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HesidosWebsite.Areas.Admin.Controllers
{
    public class MenuController : Controller
    {
        [ChildActionOnly]
        public ActionResult Index()
        {
            return View();
        }
    }
}

HesidosWebsite/Areas/Player/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HesidosWebsite.Areas.Player.Controllers
{
    public class MenuController : Controller
    {
        [ChildActionOnly]
        public ActionResult Index()
        {
            return View();
        }
    }
}

HesidosWebsite/Areas/Admin/Views/Menu/Index.cshtml
@using HesidosWebsite.Class
@{
    Layout = null;
}
<nav class="col-md-2 d-none d-md-block bg-light sidebar">
    <div class="sidebar-sticky">
        <ul class="nav flex-column">
            <li class="nav-item">
                @Html.ActionLink("← Back to Site", "Index","Home",new {area=""}, new {@class="nav-link active"})
            </li>
        </ul>
        @if (User.IsInRole(ServerRoles.Moderator))
        {
            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                <span>Moderator Tools</span>
            </h6>
            <ul class="nav flex-column">
                <li class="nav-item">
                    @Ajax.ActionLink("Chat","Index","Chat",null, new AjaxOptions(){UpdateTargetId = "DynamicContent", InsertionMode = InsertionMode.Replace}, new {@class="nav-link"})
                </li>
                <li class="nav-item">
                    @Ajax.ActionLink("Changelogs", "Changelogs", "Home", null, new AjaxOptions() {UpdateTargetId = "DynamicContent", InsertionMode = InsertionMode.Replace}, new {@class = "nav-link"})
                </li>
                <li class="nav-item">
                    @Ajax.ActionLink("Guides", "Guides", "Home", null, new AjaxOptions() {UpdateTargetId = "DynamicContent", InsertionMode = InsertionMode.Replace}, new {@class = "nav-link"})
                </li>
            </ul>
        }
        @if (User.IsInRole(ServerRoles.GameMaster))
        {
            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                <span>GameMaster Tools</span>
            </h6>
            <ul class="nav flex-column">
                <li class="nav-item">
                    @Ajax.ActionLink("Live Map", "LiveMap", "Gamemaster", null, new AjaxOptions() { UpdateTargetId = "DynamicContent", InsertionMode = InsertionMode.Replace }, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Ajax.ActionLink("Punishments", "Punishments", "Gamemaster", null, new AjaxOptions() { UpdateTargetId = "DynamicContent", InsertionMode = InsertionMode.Replace }, new { @class = "nav-link" })
                </li>
            </ul>
        }
        @if (User.IsInRole(ServerRoles.Admin))
        {
            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                <span>Admin Tools</span>
            </h6>
            <ul class="nav flex-column">
                <li class="nav-item">
                    @Ajax.ActionLink("Server Restart", "ServerRestart", "Admin", null, new AjaxOptions() { UpdateTargetId = "DynamicContent", InsertionMode = InsertionMode.Replace }, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Ajax.ActionLink("Annoucement", "Annoucement", "Admin", null, new AjaxOptions() { UpdateTargetId = "DynamicContent", InsertionMode = InsertionMode.Replace }, new { @class = "nav-link" })
                </li>
            </ul>
        }
    </div>
</nav>