HesidosWebsite/Areas/Admin/Controllers/ChatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HesidosWebsite.Class;
using WebAcess.Dao;
using WebAcess.Model;

namespace HesidosWebsite.Areas.Admin.Controllers
{
    [Authorize(Roles = ServerRoles.Moderator)]
    public class ChatController : Controller
    {
        // GET: Admin/Chat
        public ActionResult Index()
        {
            if (Request.IsAjaxRequest())
            {
                return PartialView();
            }
            return View();
        }

        public ActionResult Chat()
        {
            IList<Message> messages = new MessageDao().GetLast10Messages();

            if (Request.IsAjaxRequest())
            {
                return PartialView(messages);
            }
            return View(messages);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Post(Message message)
        {
            message.Username = new WebsiteUserDao().GetByLogin(User.Identity.Name).WebsiteName;
            message.Date = DateTime.Now;

            if (ModelState.IsValid)
            {
                new MessageDao().Create(message);
            }
            return RedirectToAction("Index");
        }
    }
}

HesidosWebsite/Controllers/HtmlHelperController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebAcess.Dao;
using WebAcess.Model;

namespace HesidosWebsite.Controllers
{
    public class HtmlHelperController : Controller
    {
        [ChildActionOnly]
        public ActionResult Index()
        {
            return View();
        }
    }
}

HesidosWebsite/Views/HtmlHelper/Index.cshtml
@using Roles = HesidosWebsite.Class.ServerRoles
@{
    Layout = null;
}
<div class="position-fixed animated fadeInLeftBig" id="logo">
    <img alt="L2Hesidos" src="@Url.Content("~/Content/Image/logo.png")" />
</div>
<nav class="navbar navbar-expand-md navbar-dark fixed-top justify-content-center">
    <div class="navbar-brand d-flex w-50 mr-auto">
        
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse w-100" id="navbarCollapse">
        <ul class="navbar-nav w-100 justify-content-center">
            <li class="nav-item active">
                @Ajax.ActionLink("Home", "Index", "Home", null, new AjaxOptions() {OnBegin = "fadeOut()", OnSuccess = "delay(data);"}, new {@class = "nav-link text-light"})
            </li>
            <li class="nav-item">
                @Ajax.ActionLink("Changelogs", "Changelog", "Home", null, new AjaxOptions() { OnBegin = "fadeOut()", OnSuccess = "delay(data);" }, new {@class = "nav-link text-light"})
            </li>
            <li class="nav-item">
                @Ajax.ActionLink("Information", "Information", "Home", null, new AjaxOptions() { OnBegin = "fadeOut()", OnSuccess = "delay(data);" }, new {@class = "nav-link text-light"})
            </li>
            <li class="nav-item">
                @Ajax.ActionLink("Rules", "Rules", "Home", null, new AjaxOptions() { OnBegin = "fadeOut()", OnSuccess = "delay(data);" }, new {@class = "nav-link text-light"})
            </li>
            @if (User.Identity.IsAuthenticated && User.IsInRole(Roles.Moderator))
            {
                <li class="nav-item">
                    @Html.ActionLink("Admin Area", "Index","Chat",new {area = "Admin"},new {@class= "nav-link text-light"})
                </li>
            }
            @if (User.Identity.IsAuthenticated && User.IsInRole(Roles.Player))
            {
                <li class="nav-item">
                    @Html.ActionLink("Player Area", "Index","Home",new {area = "Player"},new {@class= "nav-link text-light"})
                </li>
            }
        </ul>
        <ul class="nav navbar-nav ml-auto w-100 justify-content-end">
            @if (!User.Identity.IsAuthenticated)
            {
                <li class="nav-item">
                    @Ajax.ActionLink("Login", "Index", "Account", null, new AjaxOptions() { OnBegin = "fadeOut()", OnSuccess = "delay(data);" }, new {@class = "nav-link text-light"})
                </li>
                <li class="nav-item">
                    @Ajax.ActionLink("Register", "Registration", "Account", null, new AjaxOptions() { OnBegin = "fadeOut()", OnSuccess = "delay(data);" }, new {@class = "nav-link text-light"})
                </li>
            }
            else
            {
                <li class="nav-item">
                    <div class="nav-link mr-1 text-success">Logged as @User.Identity.Name</div>
                </li>
                <li class="nav-item float-right">
                    @Html.ActionLink("Logout", "Logout", "Account", null, new {@class = "nav-link text-light"})
                </li>

            }
        </ul>
    </div>
</nav>