HesidosWebsite/Areas/Admin/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HesidosWebsite.Areas.Admin.Controllers
{
    public class MenuController : Controller
    {
        [ChildActionOnly]
        public ActionResult Index()
        {
            return View();
        }
    }
}

HesidosWebsite/Controllers/HtmlHelperController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebAcess.Dao;
using WebAcess.Model;

namespace HesidosWebsite.Controllers
{
    public class HtmlHelperController : Controller
    {
        [ChildActionOnly]
        public ActionResult Index()
        {
            return View();
        }
    }
}

HesidosWebsite/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description">
    <meta name="author" content="L2Hesidos">
    <title>L2Hesidos MultiSkill</title>
    <link href="https://fonts.googleapis.com/css?family=Cinzel" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    @Scripts.Render("~/Scripts/jquery-3.3.1.min.js")
    @Scripts.Render("~/Scripts/jquery.unobtrusive-ajax.min.js")
    @Scripts.Render("~/Scripts/MicrosoftAjax.js")
    @Scripts.Render("~/Scripts/MicrosoftMvcAjax.js")
    @Scripts.Render("~/Scripts/jquery.validate.min.js")
    @Styles.Render("~/Content/bootstrap.min.css")
    @Styles.Render("~/Content/carousel.css")
    @Styles.Render("~/Content/animated.css")
    @Styles.Render("~/Content/buttons.css")
    <script src='https://www.google.com/recaptcha/api.js?render=6LdDr3YUAAAAAJYI_QiZKN6uWcMrjxjwOONUkPDx'></script>
</head>
<body>
    <header>
        @{ Html.RenderAction("Index", "HtmlHelper");}
    </header>
    <main role="main">
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img class="first-slide" src="@Url.Content("~/Content/Image/multiskill.png")" alt="New Website">
                    <div class="carousel-caption d-none d-md-block" id="firstSlideText">
                        <h5>MultiSkill</h5>
                        <p>Learn skill from all class and from our custom NPC</p>   
                    </div>
                </div>
                <div class="carousel-item">
                    <img class="second-slide" src="@Url.Content("~/Content/Image/custom.png")" alt="L2-Day">
                    <div class="carousel-caption d-none d-md-block"  id="secondSlideText">
                        <h5>Custom Items</h5>
                        <p>Custom Armors, Weapons, Jewels, Tattos, Talismans, Cloaks and much more</p>
                    </div>
                </div>
                <div class="carousel-item">
                    <img class="third-slide" src="@Url.Content("~/Content/Image/location.png")" alt="L2-Day">
                    <div class="carousel-caption d-none d-md-block"  id="thirdSlideText">
                        <h5>Custom Locations</h5>
                        <p>Custom Locations - Orbis Temple, Garden of Genesis, Windmill, Fairy Settlement</p>
                    </div>
                </div>
            </div>
            <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
        <div class="container-fluid maxWidth">
            <div class="row">
                <div class="col-lg-8" id="DynamicContent">
                    @RenderBody()
                </div>
                <div class="col-lg-4">
                    <div class="animated fadeInRightBig sidebarRight">
                        <div class="w-100 mb-5 pb-5 sidebarBlock">
                            <div class="text-center text-uppercase font-weight-bold sidebarBlockTitle">
                                <h1>Server Files</h1>
                                <div class="align-items-center">
                                    <div class="downloadButton mt-5 mr-auto ml-auto pt-4">
                                        <a href="https://mega.nz/#!BZVjgI7L!bIJp-VpomuUGkqUZSGBE-VUXs_eLEpX21s_IaIM6g8E" target="_blank">Client H5</a>
                                        <p class="downloadTop">Click to begin</p>
                                        <p class="downloadBotton">5.72GB .zip</p>
                                    </div>
                                </div>
                                <div class="align-items-center">
                                    <div class="downloadButton mt-5 mr-auto ml-auto pt-4">
                                        <a href="https://drive.google.com/open?id=1-fu2tjORwnYXN4vC0gqbpoHT1rPPvkcx" target="_blank
                                           ">System</a>
                                        <p class="downloadTop">Click to begin</p>
                                        <p class="downloadBotton">1.1GB .rar</p>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                    <div class="animated fadeInRightBig sidebarRight">
                        <div class="w-100 mb-5 pb-5 sidebarBlock">
                            <div class="text-center text-uppercase font-weight-bold sidebarBlockTitle">
                                <h1>Server Setting</h1>
                            </div>
                            <div class="row mt-5 pl-5 text-light font-weight-bold">
                                <div class="w-50">
                                    <br />
                                    XP/SP<br/>
                                    Party Bonus<br/>
                                    Quest XP/SP<br/>
                                    Drop/Spoil Chance<br/>
                                    Drop/Spoil Amount<br/>
                                    Manor<br/>
                                    Adena<br/>
                                    Seal Stone<br/>
                                    Raid Boss<br/>
                                </div>
                                <div class="w-25 text-center">
                                    Normal<br />
                                    0.5x<br/>
                                    1.5x<br/>
                                    1x<br/>
                                    1x<br/>
                                    1x<br/>
                                    3x<br/>
                                    1x<br/>
                                    1x<br/>
                                    1x<br/>
                                </div>
                                <div class="w-25 text-center">
                                    Premium<br />
                                    1x<br/>
                                    1.5x<br/>
                                    2x<br/>
                                    2x<br/>
                                    1x<br/>
                                    3x<br/>
                                    2x<br/>
                                    2x<br/>
                                    1x<br/>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="animated fadeInRightBig sidebarRight">
                        <div class="w-100 mb-5 pb-5 sidebarBlock">
                            <div class="text-center text-uppercase font-weight-bold sidebarBlockTitle">
                                <h1>Vote for us</h1>
                                <div class="row mt-5 pt-3">
                                    <div class="col">
                                        <a class="vote" href="https://l2topzone.com/vote/id/14826" target="_blank">Topzone</a>
                                    </div>
                                    <div class="col">
                                        <a class="vote" href="http://www.l2servers.com/servers/vote-29724.php" target="_blank">L2Servers</a>
                                    </div>
                                </div>
                                <div class="row mt-5">
                                    <div class="col">
                                        <a class="vote" href="http://top.l2jbrasil.com/index.php?a=in&u=L2Hesidos" target="_blank">L2JBrasil</a>
                                    </div>
                                    <div class="col">
                                        <a class="vote" href="https://vgw.hopzone.net/site/vote/102474/1" target="_blank">Hopzone</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <footer class="card-footer">
            <div class="container">
                <small>L2Hesidos.com &copy; 2017 - @DateTime.Now.Year - All rights reserved.</small><br />
                <small>IT'S ONLY TEST SERVER, ALL RIGHT BELONG TO NCSOFT.</small><br />
                <small>NCsoft, the interlocking NC logo, PlayNC and all associated logos and designs are trademarks or registered trademarks of NCsoft Corporation.</small><br />
                <small>This site is in no way associated with or endorsed by NCsoft Corporation.</small>
            </div>
        </footer>
    </main>
    <script>
        function delay(data) {
            setTimeout(function () {

                $('#DynamicContent').html(data);
            }, 300);
        }
        function fadeOut() {
            $('#DynamicContent .karta').replaceClass('fadeInLeftBig', 'fadeOutLeftBig');
        }
        (function ($) {
            $.fn.replaceClass = function (fromClass, toClass) {
                return this.removeClass(fromClass).addClass(toClass);
            };
        }(jQuery));
    </script>
    @Scripts.Render("~/Scripts/umd/popper.min.js")
    @Scripts.Render("~/Scripts/bootstrap.min.js")
    @Scripts.Render("~/Scripts/holder.min.js")
</body>
</html>

HesidosWebsite/Views/Shared/_LayoutAreas.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    @Styles.Render("~/Content/bootstrap.min.css")
    @Styles.Render("~/Content/dashboard.css")
    @Styles.Render("~/Content/animated.css")
    @Styles.Render("~/Content/summernote-bs4.css")
    @Styles.Render("~/Content/inventory.css")
    @Scripts.Render("~/Scripts/jquery-3.3.1.min.js")
    @Scripts.Render("~/Scripts/umd/popper.min.js")
    @Scripts.Render("~/Scripts/bootstrap.min.js")
    @Scripts.Render("~/Scripts/jquery.unobtrusive-ajax.min.js")
    @Scripts.Render("~/Scripts/MicrosoftAjax.js")
    @Scripts.Render("~/Scripts/MicrosoftMvcAjax.js")
    @Scripts.Render("~/Scripts/jquery.validate.min.js")
    @Scripts.Render("~/Scripts/summernote-bs4.min.js")
    <script src="https://www.paypalobjects.com/api/checkout.js"></script>
</head>
<body>
    <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
        <div class="navbar-brand col-sm-3 col-md-2 mr-0">Logged as: @User.Identity.Name</div>
        <ul class="navbar-nav px-3">
            <li class="nav-item text-nowrap">
                @Html.ActionLink("Sign out", "Logout", "Account", new { Area = "" }, new { @class = "nav-link" })
            </li>
        </ul>
    </nav>
    <div class="container-fluid">
        <div class="row">
            @{ Html.RenderAction("Index", "Menu");}
            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
                <div class="mt-2" id="DynamicContent">
                    @RenderBody()
                </div>
            </main>
        </div>
    </div>
</body>
</html>